name: flutter_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  path_provider: ^2.0.1
  path: ^1.8.0
  # tflite_flutter removed for local build/demo to avoid large native deps and R8 issues.
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  sqflite: ^2.2.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.0
  image_picker: ^1.0.0
  image: ^4.0.0
  cloudinary_public: ^0.23.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  # - assets/tflite_model.tflite
  - assets/labels.txt
